package modelo;
// Generated 03-nov-2017 9:40:22 by Hibernate Tools 5.2.5.Final

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name = "pedidos")
public class Pedidos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo_pedido")
	private Integer codigoPedido;

	@Column(name = "nombre_usuario")
	private String nombreUsuario;

	@Column(name = "fecha_pedido")
	private LocalDate fechaPedido;

	@Column(name = "hora_pedido")
	private LocalTime horaPedido;

	@Column(name = "telefono")
	private int telefono;

	@Column(name = "num_tarjeta")
	private String numTarjeta;

	@Column(name = "direccion")
	private String direccion;

	@Column(name = "codigo_postal")
	private int codigoPostal;

	public Pedidos() {
	}

	public Pedidos(String nombreUsuario, LocalDate fechaPedido, LocalTime horaPedido, int telefono, String numTarjeta,
			String direccion, int codigoPostal) {
		this.nombreUsuario = nombreUsuario;
		this.fechaPedido = fechaPedido;
		this.horaPedido = horaPedido;
		this.telefono = telefono;
		this.numTarjeta = numTarjeta;		
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
	}

	public Integer getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(Integer codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public LocalDate getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(LocalDate fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public LocalTime getHoraPedido() {
		return this.horaPedido;
	}

	public void setHoraPedido(LocalTime horaPedido) {
		this.horaPedido = horaPedido;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getNumTarjeta() {
		return this.numTarjeta;
	}

	public void setNumTarjeta(String numTarjeta) {
		this.numTarjeta = numTarjeta;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getCodigoPostal() {
		return codigoPostal;
	}

	public void setCodigoPostal(int codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

}