package modelo;
// Generated 03-nov-2017 9:40:22 by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name = "pedidos")
public class Pedidos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo_pedido")
	private Integer codigoPedido;
	
	@Column(name = "nombre_usuario")
	private int nombreUsuario;
	
	@Column(name = "fecha_pedido")
	private Date fechaPedido;
	
	@Column(name = "hora_pedido")
	private Date horaPedido;
	
	@Column(name = "telefono")
	private int telefono;
	
	@Column(name = "num_tarjeta")
	private int numTarjeta;

	public Pedidos() {
	}

	public Pedidos(int nombreUsuario, Date fechaPedido, Date horaPedido, int telefono, int numTarjeta) {
		this.nombreUsuario = nombreUsuario;
		this.fechaPedido = fechaPedido;
		this.horaPedido = horaPedido;
		this.telefono = telefono;
		this.numTarjeta = numTarjeta;
	}

	public Integer getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(Integer codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	public int getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(int nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Date getHoraPedido() {
		return this.horaPedido;
	}

	public void setHoraPedido(Date horaPedido) {
		this.horaPedido = horaPedido;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public int getNumTarjeta() {
		return this.numTarjeta;
	}

	public void setNumTarjeta(int numTarjeta) {
		this.numTarjeta = numTarjeta;
	}

}
