package modelo;
// Generated 13-oct-2017 14:16:47 by Hibernate Tools 5.2.5.Final

/**
 * ProductosPedido generated by hbm2java
 */
public class ProductosPedido implements java.io.Serializable {

	private Integer codigo;
	private int codigoPedido;
	private int codigoProducto;

	public ProductosPedido() {
	}

	public ProductosPedido(int codigoPedido, int codigoProducto) {
		this.codigoPedido = codigoPedido;
		this.codigoProducto = codigoProducto;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public int getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(int codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	public int getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(int codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

}
