package modelo;
// Generated 13-oct-2017 14:16:47 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductosPedido generated by hbm2java
 */
@Entity
@Table(name = "productos_pedido")
public class ProductosPedido implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "codigo")
	private Integer codigo;
	
	@Column(name = "codigo_pedido")
	private int codigoPedido;
	
	@Column(name = "codigo_produto")
	private int codigoProducto;

	public ProductosPedido() {
	}

	public ProductosPedido(int codigoPedido, int codigoProducto) {
		this.codigoPedido = codigoPedido;
		this.codigoProducto = codigoProducto;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public int getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(int codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	public int getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(int codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

}
