package modelo;
// Generated 13-oct-2017 14:16:47 by Hibernate Tools 5.2.5.Final

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */

@Entity
@Table(name = "usuarios")
public class Usuarios implements java.io.Serializable {
	

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "nombre_usuario")
	private String nombreUsuario;
	
	@Column(name = "rol")
	private String rol;

	@Column(name = "nombre")
	private String nombre;

	@Column(name = "apellidos")
	private String apellidos;

	@Column(name = "contraseña")
	private String contraseña;

	@Column(name = "email")
	private String email;

	@Column(name = "fecha_nacimiento")
	private LocalDate fechaNacimiento;
	

	public Usuarios() {
	}

	public Usuarios(String nombreUsuario, String rol, String nombre, String apellidos, String contraseña, String email,
			LocalDate fechaNacimiento) {
		this.nombreUsuario = nombreUsuario;
		this.rol = rol;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.contraseña = contraseña;
		this.email = email;
		this.fechaNacimiento = fechaNacimiento;
	}



	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public LocalDate getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(LocalDate fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

}
